---
title: "Simulating Age-Period-Cohort Data"
author: "Volker Schmid"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Simulating Age-Period-Cohort Data}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, cache=TRUE, out.width = "90%")
library(bamp)
```

```{r simulate_age}
age=2*sqrt(seq(1,20,length=10))
age<- age-mean(age)
plot(age, type="l")
```
```{r simulate_period}
period=15:1
period[8:15]<-8:15
period<-period/5
period<-period-mean(period)
plot(period, type="l")
```
```{r simulate_cohort}
periods_per_agegroup=5
number_of_cohorts <- periods_per_agegroup*(10-1)+15
cohort<-rep(0,60)
cohort[1:15]<-(14:0)
cohort[16:30]<- (1:15)/2
cohort[31:60]<- 8
cohort<-cohort/10
cohort<-cohort-mean(cohort)
plot(cohort, type="l")
```
```{r simulate_data}
simdata<-apcSimulate(-10, age, period, cohort, periods_per_agegroup, 1e6)
print(simdata$cases)
```

```{r bamp}
tic();simmod <- bamp(cases = simdata$cases, population = simdata$population, age = "rw2", 
period = "rw2", cohort = "rw2", periods_per_agegroup =periods_per_agegroup,method="iwls");toc()
tic();simmod2 <- bamp(cases = simdata$cases, population = simdata$population, age = "rw2", 
period = "rw2", cohort = "rw2", periods_per_agegroup =periods_per_agegroup, method="pg");toc()
```

```{r check_print_plot}
print(simmod)
print(simmod2)
checkConvergence(simmod)
checkConvergence(simmod2)
plot(simmod)
plot(simmod2)
```
```{r plot_comparison}
effects<-effects(simmod)
effects2m<-effects(simmod, mean=TRUE)
effects2<-effects(simmod2)
effects2m<-effects(simmod2, mean=TRUE)
#par(mfrow=c(3,1))
plot(age, type="l")
lines(effects$age, col="blue")
lines(effects2$age, col="green")
plot(period, type="l")
lines(effects$period, col="blue")
lines(effects2$period, col="green")
plot(cohort, type="l")
lines(effects$cohort, col="blue")
lines(effects2$cohort, col="green")
```

```{r prediction}
prediction<-predict_apc(simmod, periods=5, population=array(1e6,c(20,10)))
```

```{r prediction1}
plot(prediction$cases_period[2,], ylim=range(prediction$cases_period),ylab="",pch=19)
points(prediction$cases_period[1,],pch="–",cex=2)
points(prediction$cases_period[3,],pch="–",cex=2)
for (i in 1:20)lines(rep(i,3),prediction$cases_period[,i])
```

```{r prediction4}
plot(prediction$period[2,])
```


```{r bamp_rw2}
tic();simmodrw2 <- bamp(cases = simdata$cases, population = simdata$population, age = "rw2", 
period = "rw2", cohort = "rw2", periods_per_agegroup =periods_per_agegroup, method = "iwls");toc()
tic();simmodrw2pg <- bamp(cases = simdata$cases, population = simdata$population, age = "rw2", 
period = "rw2", cohort = "rw2", periods_per_agegroup =periods_per_agegroup, method="pg");toc()
```

```{r check_print_plot_rw2}
print(simmodrw2)
print(simmodrw2pg)
checkConvergence(simmodrw2)
checkConvergence(simmodrw2pg)
plot(simmodrw2)
plot(simmodrw2pg)
```

```{r plot_comparison}
effects<-effects(simmodrw2pg)
effects2<-effects(simmodrw2pg, mean=TRUE)
#par(mfrow=c(3,1))
plot(age, type="l")
lines(effects$age, col="blue")
lines(effects2$age, col="green")
plot(period, type="l")
lines(effects$period, col="blue")
lines(effects2$period, col="green")
plot(cohort, type="l")
lines(effects$cohort, col="blue")
lines(effects2$cohort, col="green")
```

```{r simulate_covariate_for_period}
# must be > 0; exp() keeps it positive (rnorm(15, period, .1) alone can be <= 0).
cov_p<-exp(rnorm(15,period,.1))
```

```{r bamp_with_covariate}
simmod2 <- bamp(cases = simdata$cases, population = simdata$population, age = "rw1", 
period = "rw1", cohort = "rw1", periods_per_agegroup =periods_per_agegroup,
period_covariate = cov_p, method="pg")
```
