---
title: "Simulating Age-Period-Cohort Data"
author: "Volker Schmid"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Simulating Age-Period-Cohort Data}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, cache=TRUE, out.width = "90%")
library(bamp)
```

```{r simulate_age}
age=2*sqrt(seq(1,20,length=10))
age<- age-mean(age)
plot(age, type="l")
```
```{r simulate_period}
period=15:1
period[8:15]<-8:15
period<-period/5
period<-period-mean(period)
plot(period, type="l")
```
```{r simulate_cohort}
periods_per_agegroup=5
number_of_cohorts <- periods_per_agegroup*(10-1)+15
cohort<-rep(0,60)
cohort[1:15]<-(14:0)
cohort[16:30]<- (1:15)/2
cohort[31:60]<- 8
cohort<-cohort/10
cohort<-cohort-mean(cohort)
plot(cohort, type="l")
```
```{r simulate_data}
simdata<-apcSimulate(-10, age, period, cohort, periods_per_agegroup, 1e6)
print(simdata$cases)
```

```{r bamp}
simmod <- bamp(cases = simdata$cases, population = simdata$population, age = "rw1", 
period = "rw1", cohort = "rw1", periods_per_agegroup =periods_per_agegroup)
```

```{r check_print_plot}
print(simmod)
checkConvergence(simmod)
plot(simmod)
```
```{r plot_comparison}
effects<-effects(simmod)
effects2<-effects(simmod, mean=TRUE)
#par(mfrow=c(3,1))
plot(age, type="l")
lines(effects$age, col="blue")
lines(effects2$age, col="green")
plot(period, type="l")
lines(effects$period, col="blue")
lines(effects2$period, col="green")
plot(cohort, type="l")
lines(effects$cohort, col="blue")
lines(effects2$cohort, col="green")
```

```{r}
object <- simmod
periods=5
population=array(1e6,c(20,10))
  ksi_prognose <-
    function(prepi, vdb, noa, nop, nop2, noc, zmode){
      my<-prepi[1]
      theta<-prepi[2:(noa+1)]
      phi<-prepi[(noa+2):(noa+nop2+1)]
      psi<-prepi[(noa+nop2+2):(noa+nop2+noc+1)]
      delta<-prepi[noa+nop2+noc+2]
      
      ksi<-array(0, c(nop2,noa))
      for(i in 1:noa){
        for(j in 1:nop2){
          ksi[j,i] <- my + theta[i] + phi[j] + psi[bamp::coh(i,j,noa,vdb)]
          
          if(zmode){
            ksi[j,i] <- ksi[j,i] + (rnorm(1, mean = 0, sd = 1)/sqrt(delta))
          }
        }
      }
      
      return(ksi)
    }
```
```{r}
  predict_rw <-
    function(prepi, rw, n1, n2){
      lambda<-prepi[1]
      phi<-prepi[-1]
      if(rw == 1){
        for(i in (n1+1):n2){
          phi[i] <- (rnorm(1, mean = 0, sd = 1)/sqrt(lambda)) + phi[i-1]
        }
      }
      
      if(rw == 2){
        for(i in (n1+1):n2){
          phi[i] <- (rnorm(1, mean = 0, sd = 1)/sqrt(lambda)) + (2*phi[i-1] - phi[i-2])
        }
      }
      
      if(rw == 0){
        for(i in (n1+1):n2){
          phi[i] <- phi[i-1]
        }
      }
      
      
      return(phi)
    }
  
```
```{r}
  phi<-psi<-NA
  
  a1<-dim(object$data$cases)[1]
  n1<-dim(object$data$cases)[2]
  n2<-n1+periods
  rwp<-rwc<-0
  
```
```{r}
parallel=(.Platform$OS.type != "windows")
quantiles=c(0.05,0.5,0.95)
if (!object$model$period=="")
  {
    rwp<-switch(object$model$period,
                rw1 = 1,
                rw2 = 2
    )
    ch<-length(object$samples$period)
    if(parallel)
      prep<-parallel::mclapply(1:ch, function(i,samples)cbind(object$samples$period_parameter[[i]],object$samples$period[[i]]), samples)
    if(!parallel)
      prep<-lapply(1:ch, function(i,samples)cbind(object$samples$period_parameter[[i]],object$samples$period[[i]]), samples)
    if(parallel)
      phi<-parallel::mclapply(prep, function(prepi, rw, n1, n2){t(apply(prepi, 1, predict_rw, rw, n1, n2))}, rwp, n1, n2)
    if(!parallel)
      phi<-lapply(prep, function(prepi, rw, n1, n2){t(apply(prepi, 1, predict_rw, rw, n1, n2))}, rwp, n1, n2)
  }
  
```
```{r}
  if (!object$model$cohort=="")
  {
    rwc<-switch(object$model$cohort,
                rw1 = 1,
                rw2 = 2
    )
    c1<-dim(object$samples$cohort[[1]])[2]
    c2<-bamp::coh(1,n2,a1,object$data$periods_per_agegroup)
    ch<-length(object$samples$cohort)
    if(parallel)
      prep<-parallel::mclapply(1:ch, function(i,samples)cbind(object$samples$cohort_parameter[[i]],object$samples$cohort[[i]]), samples)
    if(!parallel)
      prep<- lapply(1:ch, function(i,samples)cbind(object$samples$cohort_parameter[[i]],object$samples$cohort[[i]]), samples)
    if(parallel)
      psi<-parallel::mclapply(prep, function(prepi, rw, n1, n2){t(apply(prepi, 1, predict_rw, rw, n1, n2))}, rwc, c1, c2)
    if(!parallel)
      psi<-lapply(prep, function(prepi, rw, n1, n2){t(apply(prepi, 1, predict_rw, rw, n1, n2))}, rwc, c1, c2)
  }
  
```
```{r}
  nr.samples<-length(object$samples$intercept[[1]])
  
```
```{r}
  theta<-if(object$model$age==""){NA}else{object$samples$age}
  delta<-if(object$model$overdispersion){object$samples$overdispersion}else{NA}  
  if(parallel)
    prep<- parallel::mclapply(1:ch, function(i, theta, phi, psi, my, delta, a1, n1, c1, nr){
    theta=if(is.na(theta)){array(0, c(nr, a1))}else{theta[[i]]}
    phi=if(is.na(phi)){array(0, c(nr, a1))}else{phi[[i]]}
    psi=if(is.na(psi)){array(0, c(nr, a1))}else{psi[[i]]}
    my=my[[i]]
    delta=if(is.na(delta)){rep(0, nr)}else{delta[[i]]}
    return(cbind(my,theta,phi,psi, delta))
  },
  theta, phi, psi, object$samples$intercept, delta, a1, n1, c1, nr.samples)
  if(!parallel)
    prep<- lapply(1:ch, function(i, theta, phi, psi, my, delta, a1, n1, c1, nr){
      theta=if(is.na(theta)){array(0, c(nr, a1))}else{theta[[i]]}
      phi=if(is.na(phi)){array(0, c(nr, a1))}else{phi[[i]]}
      psi=if(is.na(psi)){array(0, c(nr, a1))}else{psi[[i]]}
      my=my[[i]]
      delta=if(is.na(delta)){rep(0, nr)}else{delta[[i]]}
      return(cbind(my,theta,phi,psi, delta))
    },
    theta, phi, psi, object$samples$intercept, delta, a1, n1, c1, nr.samples)
  
```
```{r}
  if(parallel)
    ksi<-parallel::mclapply(prep, function(prepi, vdb, noa, nop, nop2, noc, zmode){
    temp<-apply(prepi, 1, ksi_prognose, vdb, noa, nop, nop2, noc, zmode); return(array(temp,c(nop2,noa,dim(temp)[2])))}, object$data$periods_per_agegroup,
    a1, n1, n2, c2, object$model$overdispersion)
  if(!parallel)
    ksi<-lapply(prep, function(prepi, vdb, noa, nop, nop2, noc, zmode){
      temp<-apply(prepi, 1, ksi_prognose, vdb, noa, nop, nop2, noc, zmode); return(array(temp,c(nop2,noa,dim(temp)[2])))}, object$data$periods_per_agegroup,
      a1, n1, n2, c2, object$model$overdispersion)
  
```
```{r}
  ksi0<-ksi[[1]]
  for (i in 2:ch)
    ksi0<-abind::abind(ksi0,ksi[[i]], along=3)
  
  pr <- exp(ksi0)/(1+exp(ksi0))
  
  if (is.null(population))population<-object$data$population
  
  n0<-min(dim(population)[1],n2)
  
  predictedcases <- array(apply(pr,3,function(pr1,n,n0){
    return(rbinom(n0*dim(n)[2],n[1:n0,],pr1[1:n0,]))},population,n0),c(n0,dim(pr)[2:3]))
  
```
```{r}
  predictperiod<-apply(predictedcases,c(1,3),sum)

  qu_predicted_cases<-apply(predictedcases,1:2,quantile,quantiles)
  qu_predicted_pr<-apply(pr,1:2,quantile,quantiles)
  qu_predictperiod<-apply(predictperiod,1,quantile,quantiles)
  
  
  period<-phi[[1]]
  for (i in 2:ch)
    period<-abind::abind(period,phi[[i]], along=3)
  cohort<-psi[[1]]
  for (i in 2:ch)
    cohort<-abind::abind(cohort,psi[[i]], along=3)

```
```{r}
  samples<-list(
    "pr"=pr,
    "cases"=predictedcases,
    "cases_period"=predictperiod,
    "period"=period,
    "cohort"=cohort
  )
  
  predicted<-list(
    "pr"=qu_predicted_pr,
    "cases"=qu_predicted_cases,
    "cases_period"=qu_predictperiod,
    "period"=apply(period,2,quantile,quantiles),
    "cohort"=apply(cohort,2,quantile,quantiles),
    "samples"=samples
  )
```


```{r prediction}
prediction<-predict_apc(simmod, periods=5, population=array(1e6,c(20,10)))
```
```{r prediction1}
plot(prediction$cases_period[2,], ylim=range(prediction$cases_period),ylab="",pch=19)
points(prediction$cases_period[1,],pch="–",cex=2)
points(prediction$cases_period[3,],pch="–",cex=2)
for (i in 1:20)lines(rep(i,3),prediction$cases_period[,i])
```
```{r prediction4}
plot(prediction$period[2,])
```


```{r bamp_rw2}
simmodrw2 <- bamp(cases = simdata$cases, population = simdata$population, age = "rw2", 
period = "rw2", cohort = "rw2", periods_per_agegroup =periods_per_agegroup)
```

```{r check_print_plot_rw2}
print(simmodrw2)
checkConvergence(simmodrw2)
plot(simmodrw2)
```

```{r simulate_covariate_for_period}
cov_p<-rnorm(15,period,.1)
```


```{r bamp_with_covariate}
simmod2 <- bamp(cases = simdata$cases, population = simdata$population, age = "rw1", 
period = "rw1", cohort = "rw1", periods_per_agegroup =periods_per_agegroup,
period_covariate = cov_p)
```
